Feat: improve connection management and events
interledgerjs/ilp-plugin-btp pull request #18
Opened 2018-04-25 23:55 UTC by sharafian

2018-04-25 23:59 UTC, justmoon requested changes

2018-04-25 23:59 UTC, justmoon commented on index.js
> +    if (this._readyState < READY_STATES.connected) {
It's dangerous to rely on the ordering of enum values. Might be better to say explicitly `state !== connected && state !== readyToEmit`.

If you keep it this way, I would at least add a comment where the enum is defined to call out that you're relying on the ordering.

2018-04-26 00:04 UTC, justmoon approved these changes

2018-04-26 00:04 UTC, merged

2018-05-01 20:09 UTC, sentientwaffle commented on index.js
> +      this._ws.on('close', () => this._emitDisconnect())
This line causes the integration tests to fail with `test.millie ... connector:app error Error: connection aborted`.